### PR TITLE
libscreensaver: fix detection of monitor hotplug

### LINKED ISSUE #437: Can see windows on desktop before lockscreen appears when monitors turn on
### Distribution

Linux Mint 21.2 Cinnamon

### Package version

5.8.4

### Graphics hardware in use

NVIDIA GeForce RTX 3070 TI

### Frequency

Always

### Bug description

I can see the windows on my desktop before the lockscreen appears when waking my pc after the monitors turn off

### Steps to reproduce

Lock pc, wait for screen to go off and wake pc by shaking mouse, keyboard or other methods.

### Expected behavior

The lockscreen should show up and not display any windows I have open on my desktop

### Additional information

The windows also more around when waking a multiple monitor setup. e.g. I would have an IDE/browser open on one monitor and when waking up I would see it on a different monitor, then the lockscreen would appear and I would login. The window would then stay on the exact place I saw it before the lockscreen appeared.

### LINKED ISSUE #460: Security: Lockscreen bypass when resizing screen
### Distribution

Mint 22

### Package version

6.2.0

### Graphics hardware in use

Radeon 680M

### Frequency

Always

### Bug description

Cinnamon temporarily shows the desktop and allows interacting with it when the screen is resized.

This was tested using NoMachine: https://www.nomachine.com/ which effectively plugs into the real display that outputs to the HDMI port, unlike other remote desktop solutions that create virtual displays etc

In such a situation, a malicious user could potentially kill the cinnamon-screensaver process giving them full access to the desktop without knowing the password.

### Steps to reproduce

1. Lock display
2. Resize desktop by enabling remote resizing in NoMachine and then maximizing or resizing the NoMachine window
3. Desktop with all your open apps and information is visible for a few miliseconds. At this point, you can see everything that was on the desktop, and keystrokes are being passed to programs
4. Desktop is locked again shortly after

### Expected behavior

Instead of the desktop being revealed temporarily during screen resizing, the lockscreen should remain in place and block any access to the desktop.

Alternatively, it could be implemented as a black screen that captures all input while the locker restarts after the resizing operation finishes.

### Additional information

I recorded this behaviour in a video:
https://github.com/user-attachments/assets/87f195aa-6f96-4798-8a9f-67c278560ddd

The cinnamon-screensaver logs:
[cinnamon-screensaver.log](https://github.com/user-attachments/files/16849649/cinnamon-screensaver.log)

### PR DESCRIPTION
**Pull request by vamposdecampos**
When hot-adding monitors (e.g. DisplayPort), I was seeing unobscured content behind the screensaver.  Debug mode revealed:

	CsScreen received 'monitors-changed' signal from GdkScreen 25675900
	Found 2 Xinerama screens on display :0
	Monitor 0 is 0,0 1920 x 1080
	Monitor 1 is 1920,0 1920 x 1200
	Cinnamon Screensaver compiled without Solaris Xinerama support
	Scale factor of 1 applied.  Monitor 0 is 0,0 1920 x 1080
	Scale factor of 1 applied.  Monitor 1 is 1920,0 1920 x 1200
	Screen rect (0,0-3840x1200) and 2 monitor rects (0,0-503284330x1200) DO NOT add up, skipping change notification cinnamon-screensaver

This could be caused by `total_monitors` rect being uninitialized; zero it.  Might fix #437.  Seems like this could fix #460, though the log therein does _not_ say "DO NOT add up".

Ref: #437
Ref: #460
Fixes: d23d1ea "Rework behavior surrounding sleep, display changes, fractional scaling."

### CODE REVIEW

File: libcscreensaver/cs-screen-x11.c [hunk 1]
```diff
@@ -416,7 +416,7 @@ is_full_change (CsScreen *screen)
 {
     // Check to see if the union of monitor rects is the same size as the screen
 
-    GdkRectangle total_monitors;
+    GdkRectangle total_monitors = {};
```
Comment (vamposdecampos) [inline libcscreensaver/cs-screen-x11.c:419]: Zeroing worksforme, but perhaps it can have issues if there's no monitor starting at (0,0)?   That could be avoided by having `total_monitors = screen->monitor_infos[0].rect` initially.  Let me know if that's preferable, I can cook up another patch.

**Comment by clefebvre** [comment]
Can you paste what you get in debug mode after applying the patch?

File: libcscreensaver/cs-screen-x11.c (hunk 1 above)
Comment (mtwebster) [reply libcscreensaver/cs-screen-x11.c:419]: can you initialize it to `{0}` (this is the more accepted method).

This function is a sanity check for the monitor layout - the inclusive monitor rect *should* always match the screen rectangle. I may have been shooting myself in the foot here, mistaking where bad values were coming from.

Some of this also may not even be necessary anymore. The 'loop' described in d23d1ea63f ended up being a muffin issue (linuxmint/muffin@bf234250143), but I never had a chance to re-evaluate things here.


Thanks!
